In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [70]:
noise = tf.random.normal([1, 5, 5])
plt.imshow(noise[0])

In [92]:
inputs = tf.keras.layers.Input(shape=(5,5,1))
outputs = tf.keras.layers.Conv2D(5, 3, strides=1, activation='relu')(inputs)
model = tf.keras.models.Model(inputs, outputs)
model.summary()

Model: "model_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_18 (InputLayer)        [(None, 5, 5, 1)]         0         
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 3, 3, 5)           50        
Total params: 50
Trainable params: 50
Non-trainable params: 0
_________________________________________________________________


In [93]:
W = model.get_weights()
for w in W:
    print('*',w.shape)
    print(w )

* (3, 3, 1, 5)
[[[[ 0.09317827 -0.20740828 -0.15087676 -0.05265704 -0.0662252 ]]

  [[-0.24112892  0.25115785 -0.12937951  0.18143836 -0.2250344 ]]

  [[-0.29226956  0.24504438 -0.07417035 -0.06055546  0.1622467 ]]]


 [[[ 0.17623404 -0.01067504  0.09258294 -0.02091208 -0.25706372]]

  [[-0.13142332  0.11642179 -0.10649197  0.21527329 -0.05436102]]

  [[-0.05387697  0.29749444  0.0547471  -0.19308877 -0.26249003]]]


 [[[-0.17636085  0.2540432   0.09775558 -0.02670065  0.297164  ]]

  [[ 0.01861215 -0.22597107 -0.02752337  0.02866697  0.16201314]]

  [[ 0.0680581  -0.1785129   0.10377845 -0.14441967  0.21425107]]]]
* (5,)
[0. 0. 0. 0. 0.]


In [169]:
inputs = tf.keras.layers.Input(shape=(None,3))
outputs = tf.keras.layers.LSTM(1, activation='relu', return_sequences=True)(inputs)
model = tf.keras.models.Model(inputs, outputs)
model.summary()

Model: "model_54"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_61 (InputLayer)        [(None, None, 3)]         0         
_________________________________________________________________
lstm_44 (LSTM)               (None, None, 1)           20        
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [170]:
W = model.get_weights()
for w in W:
    print('*',w.shape)
    print(w )

* (3, 4)
[[-0.69515795  0.07722843  0.05704439  0.45470715]
 [ 0.39678144 -0.61505914 -0.39109534  0.51766586]
 [-0.2579937  -0.605484   -0.78593206  0.16396022]]
* (1, 4)
[[ 0.19835198  0.04056371 -0.17011628  0.9644021 ]]
* (4,)
[0. 1. 0. 0.]
